# Generated by Django 5.1.7 on 2025-03-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0003_alter_disasterreport_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasterreport',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='disasterreport',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
